- name: Create install dir
  file:
    path: "{{ onec_install_dir }}"
    state: directory
    mode: '0755'

- name: Copy rpm packages
  copy:
    src: "rpm/{{ item }}"
    dest: "{{ onec_install_dir }}/{{ item }}"
  loop: "{{ onec_packages }}"

- name: Install dependencies
  yum:
    name: "{{ onec_dependencies_common + onec_dependencies_os }}"
    state: present

- name: Install 1C packages
  yum:
    name: "{{ onec_install_dir }}/{{ item }}"
    state: present
